name = "Hyde Modified"
license = "MIT"
licenselink = "https://github.com/nmarley/hugo-theme-hyde/blob/master/LICENSE"
description = "An elegant open source and mobile first theme"
tags = ["blog", "company"]
features = ["blog", "themes"]
min_version = 0.21

[author]
    name = "Nathan Marley"
    homepage = "https://github.com/nmarley/hugo-theme-hyde"

# If Porting existing theme
[original]
    name = "spf13"
    homepage = "http://spf13.com"
